use sprout;

INSERT INTO `nation` (`nation_code`, `nation_origin_name`, `nation_name`) VALUES
('AF', 'Afghanistan', '아프가니스탄'),
('AL', 'Shqipëri', '알바니아'),
('DZ', 'الجزائر', '알제리'),
('AS', 'American Samoa', '아메리칸 사모아'),
('AD', 'Andorra', '안도라'),
('AO', 'Angola', '앙골라'),
('AI', 'Anguilla', '앵귈라'),
('AQ', 'Antarctica', '남극 대륙'),
('AG', 'Antigua and Barbuda', '앤티가 바부다'),
('AR', 'Argentina', '아르헨티나'),
('AM', 'Հայաստան', '아르메니아'),
('AW', 'Aruba', '아루바'),
('AU', 'Australia', '호주'),
('AT', 'Österreich', '오스트리아'),
('AZ', 'Azərbaycan', '아제르바이잔'),
('BS', 'Bahamas', '바하마'),
('BH', 'البحرين', '바레인'),
('BD', 'বাংলাদেশ', '방글라데시'),
('BB', 'Barbados', '바베이도스'),
('BY', 'Беларусь', '벨라루스'),
('BE', 'België', '벨기에'),
('BZ', 'Belize', '벨리즈'),
('BJ', 'Bénin', '베닌'),
('BM', 'Bermuda', '버뮤다'),
('BT', 'འབྲུག', '부탄'),
('BO', 'Bolivia', '볼리비아'),
('BA', 'Bosna i Hercegovina', '보스니아 헤르체고비나'),
('BW', 'Botswana', '보츠와나'),
('BV', 'Bouvetøya', '부베 섬'),
('BR', 'Brasil', '브라질'),
('IO', 'British Indian Ocean Territory', '영국 인도양 해외 영토'),
('BN', 'Brunei Darussalam', '브루나이'),
('BG', 'България', '불가리아'),
('BF', 'Burkina Faso', '부르키나파소'),
('BI', 'Burundi', '부룬디'),
('KH', 'កម្ពុជា', '캄보디아'),
('CM', 'Cameroon', '카메룬'),
('CA', 'Canada', '캐나다'),
('CV', 'Cabo Verde', '카보베르데'),
('KY', 'Cayman Islands', '케이맨 제도'),
('CF', 'République Centrafricaine', '중앙아프리카 공화국'),
('TD', 'Tchad', '차드'),
('CL', 'Chile', '칠레'),
('CN', '中国', '중국'),
('CX', 'Christmas Island', '크리스마스 섬'),
('CC', 'Cocos (Keeling) Islands', '코코스 제도'),
('CO', 'Colombia', '콜롬비아'),
('KM', 'Comores', '코모로'),
('CG', 'Congo', '콩고'),
('CD', 'République Démocratique du Congo', '콩고 민주 공화국'),
('CK', 'Cook Islands', '쿡 제도'),
('CR', 'Costa Rica', '코스타리카'),
('CI', 'Côte d\'Ivoire', '코트디부아르'),
('HR', 'Hrvatska', '크로아티아'),
('CU', 'Cuba', '쿠바'),
('CW', 'Curaçao', '큐라소'),
('CY', 'Κύπρος', '키프로스'),
('CZ', 'Česká republika', '체코'),
('DK', 'Danmark', '덴마크'),
('DJ', 'Djibouti', '지부티'),
('DM', 'Dominica', '도미니카'),
('DO', 'República Dominicana', '도미니카 공화국'),
('EC', 'Ecuador', '에콰도르'),
('EG', 'مصر', '이집트'),
('SV', 'El Salvador', '엘살바도르'),
('GQ', 'Guinea Ecuatorial', '적도 기니'),
('ER', 'Eritrea', '에리트레아'),
('EE', 'Eesti', '에스토니아'),
('ET', 'Ethiopia', '에티오피아'),
('FK', 'Falkland Islands', '포클랜드 제도'),
('FO', 'Føroyar', '페로 제도'),
('FJ', 'Fiji', '피지'),
('FI', 'Suomi', '핀란드'),
('FR', 'France', '프랑스'),
('GF', 'Guyane française', '프랑스령 기아나'),
('PF', 'Polynésie française', '프랑스령 폴리네시아'),
('TF', 'Terres australes et antarctiques françaises', '프랑스 남부와 남극 대륙'),
('GA', 'Gabon', '가봉'),
('GM', 'The Gambia', '감비아'),
('GE', 'საქართველო', '조지아'),
('DE', 'Deutschland', '독일'),
('GH', 'Ghana', '가나'),
('GI', 'Gibraltar', '지브롤터'),
('GR', 'Ελλάδα', '그리스'),
('GL', 'Kalaallit Nunaat', '그린란드'),
('GD', 'Grenada', '그레나다'),
('GP', 'Guadeloupe', '과들루프'),
('GU', 'Guam', '괌'),
('GT', 'Guatemala', '과테말라'),
('GG', 'Guernsey', '건지 섬'),
('GN', 'Guinée', '기니'),
('GW', 'Guiné-Bissau', '기니비사우'),
('GY', 'Guyana', '가이아나'),
('HT', 'Haïti', '아이티'),
('HM', 'Heard Island and McDonald Islands', '허드 섬과 맥도널드 제도'),
('VA', 'Città del Vaticano', '바티칸 시국'),
('HN', 'Honduras', '온두라스'),
('HK', '香港', '홍콩'),
('HU', 'Magyarország', '헝가리'),
('IS', 'Ísland', '아이슬란드'),
('IN', 'भारत', '인도'),
('ID', 'Indonesia', '인도네시아'),
('IR', 'ایران', '이란'),
('IQ', 'العراق', '이라크'),
('IE', 'Ireland', '아일랜드'),
('IM', 'Isle of Man', '맨 섬'),
('IL', 'ישראל', '이스라엘'),
('IT', 'Italia', '이탈리아'),
('JM', 'Jamaica', '자메이카'),
('JP', '日本', '일본'),
('JE', 'Jersey', '저지 섬'),
('JO', 'الأردن', '요르단'),
('KZ', 'Қазақстан', '카자흐스탄'),
('KE', 'Kenya', '케냐'),
('KI', 'Kiribati', '키리바시'),
('KP', '조선민주주의인민공화국', '북한'),
('KR', '대한민국', '대한민국'),
('KW', 'الكويت', '쿠웨이트'),
('KG', 'Кыргызстан', '키르기스스탄'),
('LA', 'ລາວ', '라오스'),
('LV', 'Latvija', '라트비아'),
('LB', 'لبنان', '레바논'),
('LS', 'Lesotho', '레소토'),
('LR', 'Liberia', '라이베리아'),
('LY', '‏ليبيا', '리비아'),
('LI', 'Liechtenstein', '리히텐슈타인'),
('LT', 'Lietuva', '리투아니아'),
('LU', 'Luxembourg', '룩셈부르크'),
('MO', '澳門', '마카오'),
('MK', 'Северна Македонија', '북마케도니아'),
('MG', 'Madagascar', '마다가스카르'),
('MW', 'Malawi', '말라위'),
('MY', 'Malaysia', '말레이시아'),
('MV', 'Maldives', '몰디브'),
('ML', 'Mali', '말리'),
('MT', 'Malta', '몰타'),
('MH', 'Marshall Islands', '마셜 제도'),
('MQ', 'Martinique', '마르티니크'),
('MR', 'Mauritanie', '모리타니'),
('MU', 'Mauritius', '모리셔스'),
('YT', 'Mayotte', '마요트'),
('MX', 'México', '멕시코'),
('FM', 'Federated States of Micronesia', '미크로네시아 연방'),
('MD', 'Republica Moldova', '몰도바'),
('MC', 'Monaco', '모나코'),
('MN', 'Монгол Улс', '몽골'),
('MS', 'Montserrat', '몬트세라트'),
('MA', 'المغرب', '모로코'),
('MZ', 'Moçambique', '모잠비크'),
('MM', 'မြန်မာ', '미얀마'),
('NA', 'Namibia', '나미비아'),
('NR', 'Nauru', '나우루'),
('NP', 'नेपाल', '네팔'),
('NL', 'Nederland', '네덜란드'),
('NC', 'Nouvelle-Calédonie', '누벨칼레도니'),
('NZ', 'New Zealand', '뉴질랜드'),
('NI', 'Nicaragua', '니카라과'),
('NE', 'Niger', '니제르'),
('NG', 'Nigeria', '나이지리아'),
('NU', 'Niue', '니우에'),
('NF', 'Norfolk Island', '노퍽 섬'),
('MP', 'Northern Mariana Islands', '북마리아나 제도'),
('NO', 'Norge', '노르웨이'),
('OM', 'عمان', '오만'),
('PK', 'پاکستان', '파키스탄'),
('PW', 'Palau', '팔라우'),
('PS', 'فلسطين', '팔레스타인'),
('PA', 'Panamá', '파나마'),
('PG', 'Papua New Guinea', '파푸아뉴기니'),
('PY', 'Paraguay', '파라과이'),
('PE', 'Perú', '페루'),
('PH', 'Pilipinas', '필리핀'),
('PN', 'Pitcairn', '핏케언 제도'),
('PL', 'Polska', '폴란드'),
('PT', 'Portugal', '포르투갈'),
('PR', 'Puerto Rico', '푸에르토리코'),
('QA', 'قطر', '카타르'),
('RE', 'La Réunion', '레위니옹'),
('RO', 'România', '루마니아'),
('RU', 'Россия', '러시아'),
('RW', 'Rwanda', '르완다'),
('BL', 'Saint-Barthélemy', '생바르텔레미'),
('SH', 'Saint Helena', '세인트헬레나'),
('KN', 'Saint Kitts and Nevis', '세인트키츠 네비스'),
('LC', 'Saint Lucia', '세인트루시아'),
('MF', 'Saint-Martin', '생마르탱'),
('PM', 'Saint Pierre and Miquelon', '생피에르 미클롱'),
('VC', 'Saint Vincent and the Grenadines', '세인트빈센트 그레나딘'),
('WS', 'Samoa', '사모아'),
('SM', 'San Marino', '산마리노'),
('ST', 'São Tomé e Príncipe', '상투메 프린시페'),
('SA', 'المملكة العربية السعودية', '사우디아라비아'),
('SN', 'Sénégal', '세네갈'),
('RS', 'Srbija', '세르비아'),
('SC', 'Seychelles', '세이셸'),
('SL', 'Sierra Leone', '시에라리온'),
('SG', 'Singapore', '싱가포르'),
('SX', 'Sint Maarten', '신트마르탠'),
('SK', 'Slovensko', '슬로바키아'),
('SI', 'Slovenija', '슬로베니아'),
('SB', 'Solomon Islands', '솔로몬 제도'),
('SO', 'Soomaaliya', '소말리아'),
('ZA', 'South Africa', '남아프리카 공화국'),
('GS', 'South Georgia and the South Sandwich Islands', '사우스조지아 사우스샌드위치 제도'),
('SS', 'South Sudan', '남수단'),
('ES', 'España', '스페인'),
('LK', 'ශ්‍රී ලංකා', '스리랑카'),
('SD', 'السودان', '수단'),
('SR', 'Suriname', '수리남'),
('SZ', 'Eswatini', '스와질란드'),
('SE', 'Sverige', '스웨덴'),
('CH', 'Schweiz', '스위스'),
('SY', 'سوريا', '시리아'),
('TW', '臺灣', '대만'),
('TJ', 'Тоҷикистон', '타지키스탄'),
('TZ', 'Tanzania', '탄자니아'),
('TH', 'ประเทศไทย', '태국'),
('TL', 'Timor-Leste', '동티모르'),
('TG', 'Togo', '토고'),
('TK', 'Tokelau', '토켈라우'),
('TO', 'Tonga', '통가'),
('TT', 'Trinidad and Tobago', '트리니다드 토바고'),
('TN', 'تونس', '튀니지'),
('TR', 'Türkiye', '터키'),
('TM', 'Türkmenistan', '투르크메니스탄'),
('TC', 'Turks and Caicos Islands', '터크스 케이커스 제도'),
('TV', 'Tuvalu', '투발루'),
('UG', 'Uganda', '우간다'),
('UA', 'Україна', '우크라이나'),
('AE', 'الإمارات العربية المتحدة', '아랍에미리트'),
('GB', 'United Kingdom', '영국'),
('US', 'United States', '미국'),
('UM', 'United States Minor Outlying Islands', '미국 해외 소속 제도'),
('UY', 'Uruguay', '우루과이'),
('UZ', 'Oʻzbekiston', '우즈베키스탄'),
('VU', 'Vanuatu', '바누아투'),
('VE', 'Venezuela', '베네수엘라'),
('VN', 'Việt Nam', '베트남'),
('VG', 'British Virgin Islands', '영국령 버진 제도'),
('VI', 'United States Virgin Islands', '미국령 버진 제도'),
('WF', 'Wallis et Futuna', '왈리스 푸투나'),
('EH', 'الصحراء الغربية', '서사하라'),
('YE', 'اليمن', '예멘'),
('ZM', 'Zambia', '잠비아'),
('ZW', 'Zimbabwe', '짐바브웨');
